### PR TITLE
Delete 'poll()' recursion call in stream

### PR DESCRIPTION
**Pull request by ark0f**
It allows to avoid `thread 'main' has overflowed its stack' error

### CODE REVIEW

**Comment by Emulator000** [comment]
@ark0f I can't reproduce this error, when you experience this error? Are you in Windows environment?

Also, what the `notify()` method does?

**Comment by ark0f** [comment]
* I get this error when telegram returns no updates (`{"ok":true,"result":[]}`) and I wait few minutes.
* Yes, I use Windows
* `notify()` says to executor call `poll()` again

**Comment by Emulator000** [comment]
@ark0f I think that this recursion is ok because it call itself and end the execution on the next "loop", by the way, maybe this is not the good way to do it as you suggested the `notify()` method.

It's a problem on Windows due to the limited stack size compared to Linux, also this happens because you are in the debug mode.

I'll review this shortly, just to be sure that this will not cause any trouble in the poll execution and I'll merge it soon.

**Comment by ark0f** [comment]
Anyway, I don't think recursion is good way as:
* Limited Windows stack size
* Something can break `poll()` logic (for example: refactor) and recursion will able to be infinite
* As I can see in [docs](https://docs.rs/futures/0.1.25/futures/task/struct.Task.html#method.notify), `notify()` is normal practic

Also my bot is working for over 1 hour with my fix against ~3 minutes without it

**Pull request merged**
